#!/opt/homebrew/bin/bash

# Kubernetes context selector using fzf
# Dependencies: kubectl, fzf

set -e

FZF_DEFAULT_OPTS=" \
--color=bg+:#414559,bg:#303446,spinner:#F2D5CF,hl:#E78284 \
--color=fg:#C6D0F5,header:#E78284,info:#CA9EE6,pointer:#F2D5CF \
--color=marker:#BABBF1,fg+:#C6D0F5,prompt:#CA9EE6,hl+:#E78284 \
--color=selected-bg:#51576D \
--color=border:#414559,label:#C6D0F5 \
--color=gutter:-1"
KUBECTL=$(which kubectl)
FZF=$(which fzf)


# Function to switch to a context
switch_context() {
    local context_name="$1"
    $KUBECTL config use-context "$context_name"
}


# Function to show interactive context selector
main() {
    # Get the contexts
    contexts=$($KUBECTL config get-contexts)
    num_contexts=$(echo "$contexts" | wc -l)

    # Calculate height based on number of contexts. add 3 for input(1) and border(2)
    height=$((num_contexts + 1))
    if [[ $height -gt 20 ]]; then
        height=20
    fi

    # Use fzf to select a context from the menu
    selected=$(echo "$contexts" | $FZF \
        --ansi \
        --header-lines=1 \
        --layout=reverse-list \
        --border=none \
        --height="$height" \
        --no-multi \
        --info=inline \
        --cycle)

    if [[ -n "$selected" ]]; then
        # Remove the prefix indicator if present
        selected=${selected#"*"}
        context_name=$(echo "$selected" | awk '{print $1}')
        switch_context "$context_name"
    else
        echo "Selection cancelled"
    fi
}

main
