#!/opt/homebrew/bin/bash

# Kubernetes context selector using fzf
# Dependencies: kubectl, fzf

set -e

KUBECTL=$(which kubectl)
FZF=$(which fzf)


# Function to switch to a context
switch_context() {
    local context_name="$1"
    $KUBECTL config use-context "$context_name"
}


# Function to show interactive context selector
main() {
    # Get the contexts
    contexts=$($KUBECTL config get-contexts)
    num_contexts=$(echo "$contexts" | wc -l)

    # Calculate height based on number of contexts. add 3 for input(1) and border(2)
    # Ensure minimum height of 13
    height=$((num_contexts + 3))
    if [[ $height -gt 20 ]]; then
        height=20
    fi

    # Use fzf to select a context from the menu
    selected=$(echo "$contexts" | $FZF \
        --ansi \
        --color=gutter:-1 \
        --header-lines=1 \
        --layout=reverse \
        --border \
        --height="$height" \
        --no-multi \
        --no-info \
        --cycle \
        --no-separator)

    if [[ -n "$selected" ]]; then
        # Remove the prefix indicator if present
        selected=${selected#"*"}
        context_name=$(echo "$selected" | awk '{print $1}')
        switch_context "$context_name"
    else
        echo "Selection cancelled"
    fi
}

main
